import skinIcon from "../../assets/images/skin.png";
import bestSellers from "../../assets/images/bestsellers.png";
import eye from "../../assets/images/eye.png";
import skin from "../../assets/images/eye-skin.png";
import sleep from "../../assets/images/sleep.png";
import tummy from "../../assets/images/tummy.png";
import hair from "../../assets/images/Omega_Color.png";
import hairInactive from "../../assets/images/Omega_Linear.png"
import bestSellersInactive from "../../assets/images/BestSellerLinear.png";
import eyeInactive from "../../assets/images/eyeLinear.png";
import skinInactive from "../../assets/images/skinLinear.png";
import sleepInactive from "../../assets/images/sleepLinear.png";
import tummyInactive from "../../assets/images/tummyLinear.png";

export const CATEGORIES_ARRAY = [
  { name: "tummy", activeImg: tummy, inActiveImg: tummyInactive },
  { name: "eye", activeImg: eye , inActiveImg: eyeInactive},
  { name: "skin", activeImg: skin , inActiveImg: skinInactive},
  { name: "sleep", activeImg: sleep, inActiveImg: sleepInactive},
  { name: "weight", activeImg: tummy, inActiveImg: tummyInactive},
  { name: "bestSeller", activeImg: bestSellers, inActiveImg: bestSellersInactive},
  { name: "hair", activeImg: hair, inActiveImg: hairInactive},
];

export const getCardSliderSettings = (length) => {
  return {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: length > 3 ? 3 : length,
    slidesToScroll: 1,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: length > 3 ? 3 : length,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: length > 2 ? 2 : length,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };
};

export const HEADER_SLIDER_SETTINGS = {
  centerMode: true,
  dots: false,
  slidesToShow: 7,
  speed: 500,
  slidesToScroll: 1,
  infinite: true,
  arrows: false,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        infinite: false,
        slidesToShow: 7,
        slidesToScroll: 1,
      },
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 7,
        slidesToScroll: 1,
        infinite: true,
      },
    },
    {
      breakpoint: 480,
      settings: {
        focusOnSelect: true,
        infinite: true,
        slidesToShow: 3,
        slidesToScroll: 5,
      },
    },
  ],
};

export const CATEGORIES_RECORDS = {
  eye: [
    {
      id: 1,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Eye",
      price: 600,
      discount: 20,
      description: "Women's health combo for better eye seight",
      rating: 4.5,
      flavour: "Orange",
    },
    {
      id: 2,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      price: 100,
      discount: 20,
      type: "Eye",
      description: "Women's health combo for better eye seight",
      rating: 4.5,
      flavour: "Orange",
    },
    {
      id: 3,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      price: 100,
      type: "Eye",
      discount: 20,
      description: "Women's health combo for better eye seight",
      rating: 4.5,
      flavour: "Orange",
    },
    {
      id: 4,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Eye",
      price: 100,
      discount: 20,
      description: "Women's health combo for better eye seight",
      rating: 4.5,
      flavour: "Orange",
    },
    {
      id: 5,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Eye",
      price: 100,
      discount: 20,
      description: "Women's health combo for better eye seight",
      rating: 4.5,
      flavour: "Orange",
    },
    {
      id: 6,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Eye",
      price: 100,
      discount: 20,
      description: "Women's health combo for better eye seight",
      rating: 4.5,
      flavour: "Orange",
    },
  ],
  hair: [
    {
      id: 7,
      photoUrl: skinIcon,
      type: "Hair",
      title: "Setu lean lite",
      price: 100,
      discount: 20,
      description: "Women's health combo for better hair quality and strength",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 8,
      photoUrl: skinIcon,
      type: "Hair",
      title: "Setu lean lite",
      price: 100,
      discount: 20,
      description: "Women's health combo for better hair quality and strength",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 9,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Hair",
      price: 100,
      discount: 20,
      description: "Women's health combo for better hair quality and strength",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 10,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Hair",
      price: 100,
      discount: 20,
      description: "Women's health combo for better hair quality and strength",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 11,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Hair",
      price: 100,
      discount: 20,
      description: "Women's health combo for better hair quality and strength",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 12,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Hair",
      price: 100,
      discount: 20,
      description: "Women's health combo for better hair quality and strength",
      rating: 3,
      flavour: "Orange",
    },
  ],
  skin: [
    {
      id: 13,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Skin",
      price: 100,
      discount: 20,
      description: "Women's health combo for better skin quality",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 14,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      price: 100,
      discount: 20,
      type: "Skin",
      description: "Women's health combo for better skin quality",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 15,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      price: 100,
      type: "Skin",
      discount: 20,
      description: "Women's health combo for better skin quality",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 16,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Skin",
      price: 100,
      discount: 20,
      description: "Women's health combo for better skin quality",
      rating: 3,
      flavour: "Orange",
    },
  ],
  tummy: [
    {
      id: 17,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      price: 100,
      type: "Tummy",
      discount: 20,
      description: "Women's health combo to lower tummy fat",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 18,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo to lower tummy fat",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 19,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo to lower tummy fat",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 20,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo to lower tummy fat",
      rating: 3,
      flavour: "Orange",
    },
  ],
  sleep: [
    {
      id: 21,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo for better sleep",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 22,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo for better sleep",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 23,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo for better sleep",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 24,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Tummy",
      price: 100,
      discount: 20,
      description: "Women's health combo for better sleep",
      rating: 3,
      flavour: "Orange",
    },
  ],
  weight: [
    {
      id: 25,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Weight",
      price: 100,
      discount: 20,
      description: "Women's health combo to reduce weight",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 26,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Weight",
      price: 100,
      discount: 20,
      description: "Women's health combo to reduce weight",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 27,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Weight",
      price: 100,
      discount: 20,
      description: "Women's health combo to reduce weight",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 28,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Weight",
      price: 100,
      discount: 20,
      description: "Women's health combo to reduce weight",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 29,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Weight",
      price: 100,
      discount: 20,
      description: "Women's health combo to reduce weight",
      rating: 3,
      flavour: "Orange",
    },
  ],
  bestSeller: [
    {
      id: 25,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Best Seller",
      price: 100,
      discount: 20,
      description: "Women's health combo to for better heath",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 26,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Best Seller",
      price: 100,
      discount: 20,
      description: "Women's health combo to for better heath",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 27,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Best Seller",
      price: 100,
      discount: 20,
      description: "Women's health combo to for better heath",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 28,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Best Seller",
      price: 100,
      discount: 20,
      description: "Women's health combo to for better heath",
      rating: 3,
      flavour: "Orange",
    },
    {
      id: 29,
      photoUrl: skinIcon,
      title: "Setu lean lite",
      type: "Best Seller",
      price: 100,
      discount: 20,
      description: "Women's health combo to for better heath",
      rating: 3,
      flavour: "Orange",
    },
  ],
};
